FROM public.ecr.aws/lambda/python:3.12

COPY services/user-service/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY shared/*.py ./
COPY services/user-service/src/ ./

CMD ["main.handler"]
